image: openjdk:24

clone:
  depth: full  # SonarQube necesita el historial completo para asignar issues correctamente

definitions:
  caches:
    sonar: ~/.sonar/cache  # Cache para SonarQube
    gradle: ~/.gradle/caches  # Cache para Gradle
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarQube Cloud
        caches:
          - gradle
          - sonar
        script:
          - apt-get update && apt-get install -y findutils
          - chmod +x gradlew
          - ./gradlew clean build test sonarqube
          - ls -R build
        artifacts:
          - build/libs/**
          - build/test-results/test/**
          - build/reports/tests/**

pipelines:
  branches:
    develop:
      - step: *build-test-sonarcloud
  pull-requests:
    '**':
      - step: *build-test-sonarcloud
