image: openjdk:21

clone:
  depth: full  # SonarQube necesita el historial completo para análisis precisos

definitions:
  caches:
    sonar: ~/.sonar/cache
    gradle: ~/.gradle

  steps:
    - step: &build-test-sonar
        name: Build, Test & SonarQube Analysis
        caches:
          - gradle
          - sonar
        script:
          - apt-get update && apt-get install -y findutils
          - chmod +x gradlew
          - ./gradlew clean build sonar --info
          - echo "Contenido del directorio build:"
          - find build/
        artifacts:
          - build/libs/**


pipelines:
  branches:
    develop:
      - step: *build-test-sonar

  pull-requests:
    '**':
      - step: *build-test-sonar
