image: openjdk:21

clone:
  depth: full

definitions:
  caches:
    sonar: ~/.sonar/cache
    gradle: ~/.gradle

  steps:
    - step: &build-test-sonar
        name: Build, Test & SonarQube Analysis
        caches:
          - gradle
          - sonar
        script:
          - apt-get update && apt-get install -y findutils
          - chmod +x gradlew
          - ./gradlew clean build sonarqube --info
          - echo "Contenido del directorio build:"
          - find build/
        artifacts:
          - build/libs/**
          - build/test-results/test/**
          - build/reports/tests/**

pipelines:
  branches:
    develop:
      - step: *build-test-sonar
    release/1.0.0:
      - step: *build-test-sonar

  pull-requests:
    '**':
      - step: *build-test-sonar
