image: openjdk:21

definitions:
  services:
    mysql:
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: teachergo
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: password

  steps:
    - step: &build-test
        name: Build, Test and Analyze
        services:
          - mysql
        caches:
          - gradle
        script:
          - export DB_HOST=127.0.0.1
          - export DB_PORT=3306
          - export DB_NAME=teachergo
          - export DB_USER=user
          - export DB_PASSWORD=password
          - chmod +x gradlew
          - ./gradlew clean build test
        artifacts:
          - build/libs/**
          - build/test-results/test/**
          - build/reports/tests/**

pipelines:
  branches:
    develop:
      - step: *build-test
