image: gradle:8.5-jdk21

definitions:
  services:
    mysql:
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: teachergo
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      caches:
      sonar: ~/.sonar/cache
  steps:
    - step: &build-test
        name: Build, Test and Analyze
        services:
          - mysql
        caches:
          - gradle
        script:


          - apt-get update
          - apt-get install -y wget unzip curl gnupg


          - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
          - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
          - apt-get update
          - apt-get install -y google-chrome-stable


          - CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
          - echo "Chrome version: $CHROME_VERSION"


          - CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          - echo "Matching ChromeDriver version: $CHROMEDRIVER_VERSION"


          - wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          - unzip /tmp/chromedriver.zip -d /usr/local/bin/
          - chmod +x /usr/local/bin/chromedriver


          - google-chrome --version
          - chromedriver --version


          - export DB_HOST=127.0.0.1
          - export DB_PORT=3306
          - export DB_NAME=teachergo
          - export DB_USER=user
          - export DB_PASSWORD=password
          - chmod +x gradlew
          - ./gradlew clean build sonar
        artifacts:
          - build/libs/**
          - build/test-results/test/**
          - build/reports/tests/**

pipelines:
  branches:
    develop:
      - step: *build-test
pull-requests:
    '**':
      - step: *build-test
